language: java

jdk:
  - oraclejdk7

env: JAVA_6_HOME=/usr/lib/jvm/java-6-openjdk-amd64 JAVA_7_HOME=/usr/lib/jvm/java-7-oracle JAVA_8_HOME=/usr/lib/jvm/java-8-oracle

install:
 - set -o pipefail
 - mvn -T 1C -Dmaven.artifact.threads=10 install -DskipTests=true -Dmaven.javadoc.skip=true -B -V | grep -Fv '[copy'

script: mvn clover2:setup test -Ptest clover2:aggregate clover2:clover -e | grep -Fv 'DEBUG' | grep -Fv '[copy'

after_success:
 - bash <(curl -s https://codecov.io/bash)